.PHONY: audit
audit:
	go fmt ./...
	go mod verify
	go vet ./...
	go run honnef.co/go/tools/cmd/staticcheck@latest -checks=all,-ST1000,-U1000 ./...
	go run golang.org/x/vuln/cmd/govulncheck@latest -show verbose ./...
	go test -race -vet=off ./...

.PHONY: code-coverage
code-coverage:
	go test -v -coverprofile /tmp/cover.out ./...
	go tool cover -html /tmp/cover.out -o /tmp/cover.html
	xdg-open /tmp/cover.html

.PHONY: benchmark
benchmark:
	go test -benchmem -bench=. ./...
